[package]
name = "fred_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fred-rs = "0.1.1"
polars = "0.25.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.14"
